#!/usr/bin/env bash
#
# Rebuild the COG fixtures and GDAL's reading of them.
#
# `tests/cog.test.js` grades this reader against GDAL value by value, the same
# way `tests/grib2.test.js` grades the GRIB decoder against ecCodes. That only
# means anything if the reference can be regenerated by someone who doubts it,
# so this is the recipe rather than a note saying the fixtures came from
# somewhere.
#
#   sudo apt-get install -y gdal-bin python3-gdal
#   tools/make-cog-fixtures.sh
#
# It reads two real 3DEP tiles over HTTP range requests — a couple of hundred
# kilobytes, not the 244 MB and 400 MB the tiles weigh — and writes into
# tests/fixtures:
#
#   cog-lzw-p3.tif        128 x 96 window, EPSG:4269, LZW + floating predictor
#   cog-deflate.tif       the same pixels, Deflate, to prove both decode alike
#   cog-utm13-1m.tif      128 x 96 window, EPSG:26913, 1 m lidar
#   cog-nodata-hole.tif   cog-lzw-p3 with a lidar-shaped hole punched in it
#   cog-trailing-ifd.tif  cog-lzw-p3 with its directories moved to the end
#   usgs-*-header.bin     the first 32 KB of each real tile, unmodified. Two
#                         projects cover the same 1 m footprint and they are not
#                         converted alike, which is the point of keeping both
#   *.gdal.json/.f32      GDAL's metadata and pixels for each fixture
#
# The tiles are named with a date and USGS re-flies ground, so a URL here can
# stop resolving. Find the current one through the TNM products API — that is
# what `dem.js` does — rather than guessing at the date in the name.

set -euo pipefail

cd "$(dirname "$0")/.."
FIX=tests/fixtures
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

S3=https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation
TILE_13="$S3/13/TIFF/historical/n40w106/USGS_13_n40w106_20260630.tif"
# Two 1 m projects cover x47y443 and they are converted differently: the 2023
# one is COG-layout, 512 to a block, nodata -999999; the 2013 one is 256 to a
# block, no COG layout, nodata float-min. Both are kept because the difference
# is the whole reason this reader may not assume a shape. The 2013 project is
# also the one with ground here — the 2023 tile is void over this window — so
# the pixel fixture is cut from it.
TILE_1M_COG="$S3/1m/Projects/CO_ArapahoRooseveltPikeNF_D23/TIFF/USGS_1M_13_x47y443_CO_ArapahoRooseveltPikeNF_D23.tif"
TILE_1M_2013="$S3/1m/Projects/CO_SoPlatteRiver_Lot5_2013/TIFF/USGS_one_meter_x47y443_CO_SoPlatteRiver_Lot5_2013.tif"

# The headers, exactly as USGS serves them, so the suite covers the real files
# and not only what GDAL writes locally.
curl -sS -r 0-32767 -o "$FIX/usgs-13-n40w106-header.bin" "$TILE_13"
curl -sS -r 0-32767 -o "$FIX/usgs-1m-x47y443-header.bin" "$TILE_1M_COG"
curl -sS -r 0-32767 -o "$FIX/usgs-1m-x47y443-2013-header.bin" "$TILE_1M_2013"

# Small windows, cut over the network. -projwin is in the source's own CRS:
# degrees for the 1/3 arc-second product, metres for the 1 m lidar.
gdal_translate -q -projwin -105.3 39.98 -105.288148 39.971111 \
  -of COG -co COMPRESS=LZW -co PREDICTOR=YES -co BLOCKSIZE=32 \
  "/vsicurl/$TILE_13" "$FIX/cog-lzw-p3.tif"

gdal_translate -q -of COG -co COMPRESS=DEFLATE -co PREDICTOR=YES -co BLOCKSIZE=32 \
  "$FIX/cog-lzw-p3.tif" "$FIX/cog-deflate.tif"

gdal_translate -q -projwin 474000 4425000 474128 4424904 \
  -of COG -co COMPRESS=LZW -co PREDICTOR=YES -co BLOCKSIZE=32 \
  "/vsicurl/$TILE_1M_2013" "$FIX/cog-utm13-1m.tif"

# A hole, because a nodata pixel read as its -999999 sentinel or flattened to
# zero puts a cliff in the terrain, and a cliff is a wind feature.
python3 tools/nodata-hole.py "$FIX/cog-lzw-p3.tif" "$FIX/cog-nodata-hole.tif"

# A legal layout that a front-only reader silently fails on.
python3 tools/trailing-ifd.py "$FIX/cog-lzw-p3.tif" "$FIX/cog-trailing-ifd.tif"
gdalinfo "$FIX/cog-trailing-ifd.tif" > /dev/null   # still a TIFF to an independent reader

python3 tools/gdal-reference.py \
  "$FIX/cog-lzw-p3" "$FIX/cog-utm13-1m" "$FIX/cog-nodata-hole"

echo "fixtures rebuilt in $FIX"
